---
kind: 'pipeline'
name: 'publish'
type: 'docker'

steps:
    - name: 'Pull existing documents'
      image: 'registry.kalehmann.de/lftp:latest'
      commands:
          - 'lftp -e "
               set ftp:ssl-force true;
               set ssl:verify-certificate yes;
               open -u $${USER},$${PASSWORD} $${SERVER};
               mirror --delete public_html/kalehmann-de/tuddmatheba $(pwd)/_site;
               exit;"'
      environment:
          USER:
              from_secret: 'ftp_user'
          PASSWORD:
              from_secret: 'ftp_password'
          SERVER:
              from_secret: 'ftp_server'
    - name: 'Build the website'
      image: 'registry.kalehmann.de/tuddmatheba:latest'
      commands:
          - 'git restore-mtime'
          - 'make'
      when:
          branch:
              - 'master'
      depends_on:
          - 'Pull existing documents'
    - name: 'Deploy the website'
      image: 'registry.kalehmann.de/lftp:latest'
      commands:
          - 'lftp -e "
               set ftp:ssl-force true;
               set ssl:verify-certificate yes;
               open -u $${USER},$${PASSWORD} $${SERVER};
               mirror --reverse --delete $(pwd)/_site public_html/kalehmann-de/tuddmatheba;
               exit;"'
      environment:
          USER:
              from_secret: 'ftp_user'
          PASSWORD:
              from_secret: 'ftp_password'
          SERVER:
              from_secret: 'ftp_server'
      depends_on:
          - 'Build the website'
      when:
          branch:
              - 'master'

image_pull_secrets:
        - 'dockerconfigjson'
...
