dist: "xenial"
language: "c"
os: "linux"

before_install:
    - "sudo apt-get install gfortran"
    - "git clone https://github.com/bats-core/bats-core.git && pushd bats-core && sudo ./install.sh /usr/local && popd"

script:
    - "pushd latex/pr10/homework/01 && make && bats tests.bats && popd"
    - "pushd latex/pr10/programme && make && bats tests.bats && popd"
