---
on: "push"  # yamllint disable-line rule:truthy

jobs:
        build-site:
                runs-on: "ubuntu-latest"
                name: "Build the site"
                steps:
                        - uses: "actions/checkout@v2"
                        - name: "Build the site"
                          uses: "./.github/actions/build-site"
                        - uses: actions/upload-artifact@v3
                          with:
                                  name: 'site'
                                  path: '_site/'
        yaml-analysis:
                runs-on: "ubuntu-latest"
                steps:
                        - uses: "actions/checkout@v2"
                        - name: "Set up Python"
                          uses: "actions/setup-python@v2"
                          with:
                                  python-version: "3.8"
                        - name: "Install yamllint"
                          run: "pip install yamllint"
                        - name: "Lint YAML files"
                          run: "yamllint --format=standard ."
...
